### ISSUE TITLE
Review comments for your DG

### ISSUE THREAD

**Issue by okkhoy** [AY2021S2-CS2113T-W09-1/tp#155]
1. better to include links to your fork ![image](https://user-images.githubusercontent.com/1023494/113077549-ee917780-9203-11eb-8499-0b43ca94f73b.png)
2. Duke? 
![image](https://user-images.githubusercontent.com/1023494/113077783-62cc1b00-9204-11eb-843f-bf5eba2c8b08.png)
3. Parser component class diagram: consider removing non-critical attributes and methods. It looks pretty cluttered 
![image](https://user-images.githubusercontent.com/1023494/113078186-29e07600-9205-11eb-84e2-5eed647b8423.png)
4. 1 -> one  ![image](https://user-images.githubusercontent.com/1023494/113078231-44b2ea80-9205-11eb-8a91-2d74ca8a1f3d.png)
5. Possibly use code formatting (with back ticks)? 
![image](https://user-images.githubusercontent.com/1023494/113078326-70ce6b80-9205-11eb-9f7b-17bb53c5ed58.png)
6. indicate that these two paths are due to exception 
![image](https://user-images.githubusercontent.com/1023494/113078448-b428da00-9205-11eb-88d7-5a19724b2fcc.png)
7. Possible to split to a couple of diagrams? Improves redability 
![image](https://user-images.githubusercontent.com/1023494/113078734-44671f00-9206-11eb-94ed-af9e9682908f.png)
8. Which class is using the enumeration? 
![image](https://user-images.githubusercontent.com/1023494/113078805-69f42880-9206-11eb-80ab-cf3aa871a29d.png)
9. Good use of UML notes. Other class diagrams can use this technique to simplify 
![image](https://user-images.githubusercontent.com/1023494/113078864-885a2400-9206-11eb-9b30-be029f14a135.png)
1. ??? 
![image](https://user-images.githubusercontent.com/1023494/113079051-ec7ce800-9206-11eb-9aff-f43b59c60a66.png)
1. To complete (a few subsections also like this) 
![image](https://user-images.githubusercontent.com/1023494/113079190-29e17580-9207-11eb-82c5-4da3574558f3.png)

**Comment by jonahtwl** [comment]
All done!
