### ISSUE TITLE
Fix multiple bugs identified from PE-D

### ISSUE THREAD

**Issue by marklowsk** [AY2021S2-CS2113T-W09-1/tp#204]
List for Andy:
* Fix amount validation to allow up to 2 decimal places (to mimic money).
* Amount should have the dollar or cent value entered explicitly to avoid confusion.
* `help` output should be more user friendly.

**Comment by LeeHanYongAndy** [comment]
Fixes #197 to address amount validation.
Fixes #198 to address help output
