### ISSUE TITLE
As a Debt Collector (Student), I want to list down a list of people who owes me money with a deadline

### ISSUE THREAD

**Issue by tzexern** [AY2021S2-CS2113T-W09-1/tp#33]
... so that I can make sure that they return their money.

**Comment by LeeHanYongAndy** [comment]
Hi Jason, your user story is nicely crafted with the user, needs, and reason of needs.

Fixes #33

**Comment by LeeHanYongAndy** [comment]
Reopen - close only after V1.0 is working.
