### ISSUE TITLE
As a SOC Student, I want a CLI styled money management system

### ISSUE THREAD

**Issue by jonahtwl** [AY2021S2-CS2113T-W09-1/tp#37]
... so that it would be faster for me to type on a CLI compared to clicking on a GUI.

**Comment by LeeHanYongAndy** [comment]
Hi, @tzexern can you kindly please close this issue for us? Our team have completed v1.0.

**Comment by tzexern** [comment]
Yep, no problem buddy.
The test run looked fine.
