### ISSUE TITLE
Update parser to parse without an option

### ISSUE THREAD

**Issue by marklowsk** [AY2021S2-CS2113T-W09-1/tp#94]
parser v2.0 that allows parsing without an option infront of a text.
Example:
Old: `remove 7` -> `[remove 7]`.
New: `remove 7` -> `[remove, 7]`.

**Comment by jonahtwl** [comment]
We are removing the index (-i) option right?

**Comment by marklowsk** [comment]
Yes, e.g. from `remove -i 7` to `remove 7`.

**Comment by LeeHanYongAndy** [comment]
Update: closed due to keeping -i feature.
